### ISSUE TITLE
Please support fastify `^4.0.0`

### ISSUE THREAD

**Issue by puzzle9** [hsynlms/sequelize-fastify#8]
```
FastifyError [Error]: fastify-plugin: sequelize-fastify - expected '3.x' fastify version, '4.0.0' is installed
    at Object.checkVersion (/project/node_modules/fastify/lib/pluginUtils.js:108:11)
    at Object.registerPlugin (/project/node_modules/fastify/lib/pluginUtils.js:123:16)
    at Boot.override (/project/node_modules/fastify/lib/pluginOverride.js:28:57)
    at Plugin.exec (/project/node_modules/avvio/plugin.js:80:33)
    at Boot.loadPlugin (/project/node_modules/avvio/plugin.js:273:10)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'FST_ERR_PLUGIN_VERSION_MISMATCH',
  statusCode: 500
}

```

**Comment by hsynlms** [comment]
Shipped with v2.0.0

https://github.com/hsynlms/sequelize-fastify/commit/25af4ba7466e27d00510087859f207417efdcd96
